// Generated by gencpp from file msgs_traffic/TrafficSignArray.msg
// DO NOT EDIT!


#ifndef MSGS_TRAFFIC_MESSAGE_TRAFFICSIGNARRAY_H
#define MSGS_TRAFFIC_MESSAGE_TRAFFICSIGNARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <msgs_traffic/TrafficSign.h>

namespace msgs_traffic
{
template <class ContainerAllocator>
struct TrafficSignArray_
{
  typedef TrafficSignArray_<ContainerAllocator> Type;

  TrafficSignArray_()
    : header()
    , signs()  {
    }
  TrafficSignArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , signs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::msgs_traffic::TrafficSign_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::msgs_traffic::TrafficSign_<ContainerAllocator> >> _signs_type;
  _signs_type signs;





  typedef boost::shared_ptr< ::msgs_traffic::TrafficSignArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgs_traffic::TrafficSignArray_<ContainerAllocator> const> ConstPtr;

}; // struct TrafficSignArray_

typedef ::msgs_traffic::TrafficSignArray_<std::allocator<void> > TrafficSignArray;

typedef boost::shared_ptr< ::msgs_traffic::TrafficSignArray > TrafficSignArrayPtr;
typedef boost::shared_ptr< ::msgs_traffic::TrafficSignArray const> TrafficSignArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgs_traffic::TrafficSignArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgs_traffic::TrafficSignArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgs_traffic::TrafficSignArray_<ContainerAllocator1> & lhs, const ::msgs_traffic::TrafficSignArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.signs == rhs.signs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgs_traffic::TrafficSignArray_<ContainerAllocator1> & lhs, const ::msgs_traffic::TrafficSignArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgs_traffic

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::msgs_traffic::TrafficSignArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_traffic::TrafficSignArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs_traffic::TrafficSignArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs_traffic::TrafficSignArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_traffic::TrafficSignArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_traffic::TrafficSignArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgs_traffic::TrafficSignArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52473d5a9fb0a322cd148dfb905888a7";
  }

  static const char* value(const ::msgs_traffic::TrafficSignArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52473d5a9fb0a322ULL;
  static const uint64_t static_value2 = 0xcd148dfb905888a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::msgs_traffic::TrafficSignArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgs_traffic/TrafficSignArray";
  }

  static const char* value(const ::msgs_traffic::TrafficSignArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgs_traffic::TrafficSignArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"msgs_traffic/TrafficSign[] signs\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: msgs_traffic/TrafficSign\n"
"#traffic sign classification\n"
"uint8 type\n"
"string name\n"
"msgs_traffic/signs list\n"
"\n"
"#traffic sign semantic\n"
"float64 value\n"
"msgs_traffic/traffic_light traffic_light\n"
"\n"
"#traffic sign localization \n"
"geometry_msgs/PoseStamped pose\n"
"float64 length\n"
"uint32 road_id \n"
"uint32[] lanes\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: msgs_traffic/signs\n"
"#list of all traffic signs\n"
"\n"
"uint8 UNKNOWN             = 0\n"
"uint8 STOP                = 1\n"
"uint8 SPEED_LIMIT         = 2\n"
"uint8 PEDESTRIAN_CROSSING = 3\n"
"uint8 SPEED_BUMP          = 4\n"
"uint8 TRAFFIC_LIGHT       = 5\n"
"\n"
"================================================================================\n"
"MSG: msgs_traffic/traffic_light\n"
"uint8 RED    = 0\n"
"uint8 GREEN  = 1\n"
"uint8 YELLOW = 2\n"
"\n"
"uint8 color\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::msgs_traffic::TrafficSignArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgs_traffic::TrafficSignArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.signs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrafficSignArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgs_traffic::TrafficSignArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgs_traffic::TrafficSignArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "signs[]" << std::endl;
    for (size_t i = 0; i < v.signs.size(); ++i)
    {
      s << indent << "  signs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::msgs_traffic::TrafficSign_<ContainerAllocator> >::stream(s, indent + "    ", v.signs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGS_TRAFFIC_MESSAGE_TRAFFICSIGNARRAY_H
