// Generated by gencpp from file msgs_mapping/HDMap.msg
// DO NOT EDIT!


#ifndef MSGS_MAPPING_MESSAGE_HDMAP_H
#define MSGS_MAPPING_MESSAGE_HDMAP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseWithCovarianceStamped.h>

namespace msgs_mapping
{
template <class ContainerAllocator>
struct HDMap_
{
  typedef HDMap_<ContainerAllocator> Type;

  HDMap_()
    : header()
    , XML_HDMap()
    , pose()  {
    }
  HDMap_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , XML_HDMap(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _XML_HDMap_type;
  _XML_HDMap_type XML_HDMap;

   typedef  ::geometry_msgs::PoseWithCovarianceStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::msgs_mapping::HDMap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgs_mapping::HDMap_<ContainerAllocator> const> ConstPtr;

}; // struct HDMap_

typedef ::msgs_mapping::HDMap_<std::allocator<void> > HDMap;

typedef boost::shared_ptr< ::msgs_mapping::HDMap > HDMapPtr;
typedef boost::shared_ptr< ::msgs_mapping::HDMap const> HDMapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgs_mapping::HDMap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgs_mapping::HDMap_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgs_mapping::HDMap_<ContainerAllocator1> & lhs, const ::msgs_mapping::HDMap_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.XML_HDMap == rhs.XML_HDMap &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgs_mapping::HDMap_<ContainerAllocator1> & lhs, const ::msgs_mapping::HDMap_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgs_mapping

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::msgs_mapping::HDMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_mapping::HDMap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs_mapping::HDMap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs_mapping::HDMap_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_mapping::HDMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_mapping::HDMap_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgs_mapping::HDMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f28f659f2e5da98f786a894149a1b462";
  }

  static const char* value(const ::msgs_mapping::HDMap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf28f659f2e5da98fULL;
  static const uint64_t static_value2 = 0x786a894149a1b462ULL;
};

template<class ContainerAllocator>
struct DataType< ::msgs_mapping::HDMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgs_mapping/HDMap";
  }

  static const char* value(const ::msgs_mapping::HDMap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgs_mapping::HDMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string XML_HDMap\n"
"geometry_msgs/PoseWithCovarianceStamped pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovarianceStamped\n"
"# This expresses an estimated pose with a reference coordinate frame and timestamp\n"
"\n"
"Header header\n"
"PoseWithCovariance pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::msgs_mapping::HDMap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgs_mapping::HDMap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.XML_HDMap);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HDMap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgs_mapping::HDMap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgs_mapping::HDMap_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "XML_HDMap: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.XML_HDMap);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseWithCovarianceStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGS_MAPPING_MESSAGE_HDMAP_H
