(cl:in-package msgs_perception-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          NS-VAL
          NS
          POSE-VAL
          POSE
          TWIST-VAL
          TWIST
          LINEAR_ACCELERATION-VAL
          LINEAR_ACCELERATION
          SCALE-VAL
          SCALE
          POINT_CLOUD-VAL
          POINT_CLOUD
          CLASS_ID-VAL
          CLASS_ID
          CLASSES-VAL
          CLASSES
          BBOX-VAL
          BBOX
          ONCOMING-VAL
          ONCOMING
          LAT_RATE-VAL
          LAT_RATE
          TRACK_STATUS-VAL
          TRACK_STATUS
          BRIDGE_OBJECT-VAL
          BRIDGE_OBJECT
          COLOR-VAL
          COLOR
          LIFETIME-VAL
          LIFETIME
          FRAME_LOCKED-VAL
          FRAME_LOCKED
          ANIMATION_SPEED-VAL
          ANIMATION_SPEED
          ACTION-VAL
          ACTION
          TYPE-VAL
          TYPE
          VEHICLE_MODEL-VAL
          VEHICLE_MODEL
))