// Generated by gencpp from file msgs_action/SteeringAngle.msg
// DO NOT EDIT!


#ifndef MSGS_ACTION_MESSAGE_STEERINGANGLE_H
#define MSGS_ACTION_MESSAGE_STEERINGANGLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace msgs_action
{
template <class ContainerAllocator>
struct SteeringAngle_
{
  typedef SteeringAngle_<ContainerAllocator> Type;

  SteeringAngle_()
    : header()
    , angle(0.0)  {
    }
  SteeringAngle_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::msgs_action::SteeringAngle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgs_action::SteeringAngle_<ContainerAllocator> const> ConstPtr;

}; // struct SteeringAngle_

typedef ::msgs_action::SteeringAngle_<std::allocator<void> > SteeringAngle;

typedef boost::shared_ptr< ::msgs_action::SteeringAngle > SteeringAnglePtr;
typedef boost::shared_ptr< ::msgs_action::SteeringAngle const> SteeringAngleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgs_action::SteeringAngle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgs_action::SteeringAngle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgs_action::SteeringAngle_<ContainerAllocator1> & lhs, const ::msgs_action::SteeringAngle_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgs_action::SteeringAngle_<ContainerAllocator1> & lhs, const ::msgs_action::SteeringAngle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgs_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::msgs_action::SteeringAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_action::SteeringAngle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs_action::SteeringAngle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs_action::SteeringAngle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_action::SteeringAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_action::SteeringAngle_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgs_action::SteeringAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84c1d14f72a90efbf3b1a4de632c5bfb";
  }

  static const char* value(const ::msgs_action::SteeringAngle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84c1d14f72a90efbULL;
  static const uint64_t static_value2 = 0xf3b1a4de632c5bfbULL;
};

template<class ContainerAllocator>
struct DataType< ::msgs_action::SteeringAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgs_action/SteeringAngle";
  }

  static const char* value(const ::msgs_action::SteeringAngle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgs_action::SteeringAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This represents the angle of steering system (in radians).  \n"
"\n"
"Header header\n"
"float64 angle\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::msgs_action::SteeringAngle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgs_action::SteeringAngle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SteeringAngle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgs_action::SteeringAngle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgs_action::SteeringAngle_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGS_ACTION_MESSAGE_STEERINGANGLE_H
