(cl:defpackage msgs_navigation-msg
  (:use )
  (:export
   "<EMERGENCYSTOP>"
   "EMERGENCYSTOP"
   "<EMERGENCYSTOP>"
   "EMERGENCYSTOP"
   "<GLOBALPLAN>"
   "GLOBALPLAN"
   "<GLOBALPLAN>"
   "GLOBALPLAN"
   "<PATH>"
   "PATH"
   "<PATH>"
   "PATH"
   "<SPEEDCONSTRAINT>"
   "SPEEDCONSTRAINT"
   "<SPEEDCONSTRAINT>"
   "SPEEDCONSTRAINT"
   "<TRAJECTORYERROR>"
   "TRAJECTORYERROR"
   "<TRAJECTORYERROR>"
   "TRAJECTORYERROR"
   "<TRAJECTORYPOINT>"
   "TRAJECTORYPOINT"
   "<TRAJECTORYPOINT>"
   "TRAJECTORYPOINT"
  ))

